language: android
jdk: oraclejdk8

env:
   global:
      - ANDROID_API_LEVEL=28
      - ANDROID_BUILD_TOOLS_VERSION=28.0.3

android:
   components:
      - build-tools-$ANDROID_BUILD_TOOLS_VERSION
      - android-$ANDROID_API_LEVEL    
      - extra

script:
   - ./graldew build check
